# ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-spark-spark-operator-controller
  namespace: spark
---
# Role with expanded permissions (including patch for services)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-operator-role
  namespace: spark
rules:
  - apiGroups: [""]
    resources:
      - pods
      - pods/log
      - events
      - services
      - configmaps
      - persistentvolumeclaims
    verbs:
      - create
      - get
      - watch
      - list
      - delete
      - patch
      - update   # Added for completeness (often needed with patch)
  - apiGroups: ["batch", "extensions"]
    resources: ["jobs"]
    verbs:
      - create
      - get
      - watch
      - list
      - delete
  - apiGroups: ["sparkoperator.k8s.io"]
    resources:
      - sparkapplications
      - scheduledsparkapplications
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
# RoleBinding to bind Role to ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-operator-role-binding
  namespace: spark
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spark-operator-role
subjects:
  - kind: ServiceAccount
    name: my-spark-spark-operator-controller
    namespace: spark
---
# ClusterRole for SparkConnect CRDs
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spark-operator-sparkconnect
rules:
  - apiGroups: ["sparkoperator.k8s.io"]
    resources: ["sparkconnects"]
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
# ClusterRoleBinding for SparkConnect access
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spark-operator-sparkconnect-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spark-operator-sparkconnect
subjects:
  - kind: ServiceAccount
    name: my-spark-spark-operator-controller
    namespace: spark
